tasks: 
- before: npm install -g prebuild-install
  init: npm install -g @zowe/cli@zowe-v2-lts
  command: zowe plugins install @zowe/cics-for-zowe-cli@zowe-v2-lts @zowe/db2-for-zowe-cli@zowe-v2-lts @zowe/ims-for-zowe-cli@zowe-v2-lts @zowe/mq-for-zowe-cli@zowe-v2-lts @zowe/zos-ftp-for-zowe-cli@zowe-v2-lts

vscode:
  extensions: 
    - broadcomMFD.bridge-for-git-explorer
    - broadcomMFD.code4z-extension-pack
    - Zowe.vscode-extension-for-zowe
